# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.tdmi
canonical: https://interop.esante.gouv.fr/ig/fhir/tdmi # the last part of canonical and id must be the same
name: TDMI # Should be an acronym
title: Traçabilité des Dispositifs Médicaux Implantables
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 3.0.0-ballot # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: public-comment # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"
dependencies:
    hl7.fhir.fr.core: 2.1.0
    ans.fhir.fr.tde: 2.0.0-ballot
parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension




pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Volume 1 - Etude fonctionnelle
    specifications_techniques_introduction.md:
        title: Volume 2 - Détail des transactions
        specifications_techniques_construction_flux.md:
            title: Construction des flux
        specifications_techniques_flux23_flux24.md:
            title: Flux 23 - Flux 24
        specifications_techniques_flux25_flux26.md:
            title: Flux 25 - Flux 26
    autres_ressources.md:
        title: Autres Ressources
        norme_standard.md:
            title: Normes et Standards
        annexe_mise_en_correspondance.md:
            title: Mise en correspondance
        glossaire.md:
            title: Glossaire
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    change-log.md:
        title: Historique des versions

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: specifications_fonctionnelles.html
    Volume 2 - Détail des transactions:
        Introduction: specifications_techniques_introduction.html
        Construction des flux: specifications_techniques_construction_flux.html
        Flux 23 - Flux 24: specifications_techniques_flux23_flux24.html
        Flux 25- Flux 26: specifications_techniques_flux25_flux26.html
    Volume 3 - Annexes:
        Normes et Standards: norme_standard.html
        Mise en correspondance: annexe_mise_en_correspondance.html
        Glossaire: glossaire.html
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Ressources de conformité: artifacts.html
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: change-log.html
