# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.tdmi
canonical: https://interop.esante.gouv.fr/ig/fhir/tdmi # the last part of canonical and id must be the same
name: TDMI # Should be an acronym
title: Traçabilité des Dispositifs Médicaux Implantables
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 3.0.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension




pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Volume 1 - Etude fonctionnelle
    specifications_techniques_introduction.md:
        title: Volume 2 - Détail des transactions
        specifications_techniques_construction_flux.md:
            title: Construction des flux
        specifications_techniques_flux23_recherche_traces.md:
            title: Flux 23 - RechercheTraces
        specifications_techniques_flux24_reponse_recherche_traces.md:
            title: Flux 24 - RéponseRechercheTraces
        specifications_techniques_flux25_consulter_trace.md:
            title: Flux 25 - ConsulterTrace
        specifications_techniques_flux26_reponse_consulter_trace.md:
            title: Flux 26 - ReponseConsulterTrace
    autres_ressources.md:
        title: Autres Ressources
        norme_standard.md:
            title: Normes et Standards
        glossaire.md:
            title: Glossaire
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    change-log.md:
        title: Historique des versions

menu:
    Accueil: index.html
    Volume 1 - Etude fonctionnelle: specifications_fonctionnelles.html
    Volume 2 - Détail des transactions:
        Introduction: specifications_techniques_introduction.html
        Construction des flux: specifications_techniques_construction_flux.html
        RechercheTraces: specifications_techniques_flux23_recherche_traces.html
        RéponseRechercheTraces: specifications_techniques_flux24_reponse_recherche_traces.html
        ConsulterTrace: specifications_techniques_flux25_consulter_trace.html
        ReponseConsulterTrace: specifications_techniques_flux26_reponse_consulter_trace.html
    Volume 3 - Annexes:
        Normes et Standards: norme_standard.html
        Glossaire: glossaire.html
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Ressources de conformité: artifacts.html
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
    Historique: change-log.html
